const mongoose = require('mongoose');

// Cached neural-TTS audio for a question's SPOKEN EXPLANATION (separate from
// QuestionAudio, which caches the question text). Generated by the admin Voice
// page and served by GET /api/v1/assessment/questions/:id/explanation-audio.
// `textHash` records the exact (post-transliteration) text the audio was made
// from, so editing the explanation — or toggling its Tanglish flag — is detected
// as stale and the candidate transparently falls back to browser speech until
// it's regenerated. One record per question (the explanation is one field).
const explanationAudioSchema = new mongoose.Schema({
  questionId:  { type: mongoose.Schema.Types.ObjectId, ref: 'Question', required: true, unique: true },
  textHash:    { type: String, required: true },
  voice:       { type: String, required: true },
  lang:        { type: String, required: true },
  contentType: { type: String, default: 'audio/mpeg' },
  audio:       { type: Buffer, required: true },
}, { timestamps: true });

module.exports = mongoose.model('ExplanationAudio', explanationAudioSchema);
